### ISSUE TITLE
matrix_inv() has causes error

### ISSUE THREAD

**Issue by bluenlive** [Tee0125/snippet#1]
Hi, thank you for your code.
I'm studying with it.

BTW, matrix_inv() in matrix.c has an error.

If maximum value of 1st columns is 0, it cannot calculate it.

ex)
-0.5, 0.5, -0.5
 0.0, 0.0, 0.5
-1.5, 0.5, 0.5 

Could you fix this error please?

**Comment by Tee0125** [comment]
the issue is fixed :)

pull my commit and check again please.
